/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Chris (https://sketchfab.com/cebbi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/isometric-world-c174ea7809c64fbebf6795f1fbfafb90
title: Isometric World
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/world.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Boden_1.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Boden_2.geometry} material={materials.Floor2} />
        <mesh geometry={nodes.Boden_3.geometry} material={materials.Floor3} />
        <mesh geometry={nodes.Boden_4.geometry} material={materials.Floor4} />
        <group position={[0, 0, 0.12]}>
          <mesh geometry={nodes.Strasse_1.geometry} material={materials.Strasse} />
          <mesh geometry={nodes.Strasse_2.geometry} material={materials.Steifen} />
        </group>
        <group position={[0, 0.27, 0.13]} scale={[1, 0.01, 3.14]}>
          <mesh geometry={nodes.Rechts_1.geometry} material={materials.Strasse2} />
        </group>
        <group position={[0, -0.26, 0.13]} scale={[1, 0.01, 3.14]}>
          <mesh geometry={nodes.Rechts_2.geometry} material={materials.Strasse2} />
        </group>
        <group position={[-0.19, 0.13, 0.19]}>
          <mesh geometry={nodes.Auto_1.geometry} material={materials.Reifen} />
          <mesh geometry={nodes.Auto_2.geometry} material={materials.Fenster} />
          <mesh geometry={nodes.Auto_3.geometry} material={materials.Auto1} />
        </group>
        <group position={[0, 0.58, 0.07]} rotation={[0, 0, 0.06]} scale={0.08}>
          <mesh geometry={nodes.Cone012_1.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_2.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.65, 0.76, 0.1]} rotation={[0, 0, -0.75]} scale={0.08}>
          <mesh geometry={nodes.Cone012_3.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_4.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.41, 0.45, 0.06]} rotation={[0, 0, -0.47]} scale={0.08}>
          <mesh geometry={nodes.Cone012_5.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_6.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.72, 0.76, 0.04]} scale={0.08}>
          <mesh geometry={nodes.Cone012_7.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_8.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.44, 0.52, 0.11]} rotation={[0, 0, -0.44]} scale={0.08}>
          <mesh geometry={nodes.Cone012_9.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_10.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.25, 0.86, 0.07]} rotation={[0, 0, -0.64]} scale={0.08}>
          <mesh geometry={nodes.Cone012_11.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_12.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.36, 0.86, 0.08]} rotation={[0, 0, -0.97]} scale={0.08}>
          <mesh geometry={nodes.Cone012_13.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_14.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.75, -0.48, 0.06]} rotation={[0, 0, -1.2]} scale={0.08}>
          <mesh geometry={nodes.Cone012_15.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_16.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.22, -0.67, 0.05]} rotation={[0, 0, -0.97]} scale={0.08}>
          <mesh geometry={nodes.Cone012_17.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_18.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.35, -0.56, 0.09]} rotation={[0, 0, -0.97]} scale={0.08}>
          <mesh geometry={nodes.Cone012_19.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_20.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.77, -0.48, 0.06]} rotation={[0, 0, -0.3]} scale={0.08}>
          <mesh geometry={nodes.Cone012_21.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_22.geometry} material={materials.Stamm} />
        </group>
        <group position={[0.62, -0.8, 0.1]} rotation={[0, 0, 0.13]} scale={0.08}>
          <mesh geometry={nodes.Cone012_23.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_24.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.57, -0.81, 0.1]} rotation={[0, 0, -0.01]} scale={0.08}>
          <mesh geometry={nodes.Cone012_25.geometry} material={materials.Baum} />
          <mesh geometry={nodes.Cone012_26.geometry} material={materials.Stamm} />
        </group>
        <group position={[-0.48, -0.6, 0.22]} rotation={[0, 0, -Math.PI / 2]} scale={[0.07, 0.03, 0.03]}>
          <mesh geometry={nodes.Cube_1.geometry} material={materials.material} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials.Reh2} />
        </group>
        <group position={[0.04, -0.92, 0.05]} scale={[0.52, 0.46, 0.46]}>
          <mesh geometry={nodes.Wasser_1.geometry} material={materials.wasser} />
        </group>
        <group position={[-0.7, 0.3, 0.73]} rotation={[0, 0, 0.04]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_1.geometry} material={materials.Vogel} />
        </group>
        <group position={[-0.42, 0.56, 0.64]} rotation={[0, 0, -0.07]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_2.geometry} material={materials.Vogel} />
        </group>
        <group position={[0.69, 0.63, 0.69]} rotation={[0, 0, -0.04]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_3.geometry} material={materials.Vogel} />
        </group>
        <group position={[0.15, 0.8, 0.79]} rotation={[0, 0, -0.03]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_4.geometry} material={materials.Vogel} />
        </group>
        <group position={[-0.58, 0.49, 0.69]} rotation={[0, 0, 0.17]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_5.geometry} material={materials.Vogel} />
        </group>
        <group position={[0.41, 0.66, 0.73]} rotation={[0, 0, 0.16]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_6.geometry} material={materials.Vogel} />
        </group>
        <group position={[-0.06, 0.54, 0.79]} rotation={[0, 0, 0.08]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_7.geometry} material={materials.Vogel} />
        </group>
        <group position={[0.21, 0.53, 0.64]} rotation={[0, 0, -0.08]} scale={0.13}>
          <mesh geometry={nodes.Vogel007_8.geometry} material={materials.Vogel} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/world.gltf')
